name: Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
jobs:
  build-docker-image:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker-compose --file docker-compose.debug --tag bddtest-live:$(date +%s) --build